stack_size:
  aperiodic_process: 15000
virtual_links:
  - id: 2
    rate: 500ms
    msg_size: 100
    ports:
      - !SamplingPortSource
        channel: EchoReplyCl
  - id: 1
    rate: 1s
    msg_size: 100B
    interfaces: [ "veth0" ]
    ports:      
      - !SamplingPortDestination
        channel: EchoRequestCl
        validity: 2s
interfaces:
  - id: 1
    name: veth0
    rate: 1000
    mtu: 1500
    # TODO remove. not needed for veth, only for UDP
    destination: "127.0.0.1:34256"
