stack_size:
  aperiodic_process: 1MB
virtual_links:
  - id: 1
    msg_size: 100B
    interfaces: [ "34255" ]
    ports:      
      - !SamplingPortDestination
        channel: EchoRequest
        validity: 2s
  - id: 2
    msg_size: 100B
    ports:
      - !SamplingPortSource
        channel: EchoReply
interfaces:
  - !Udp
    id: 1
    name: "34255"
    rate: 10000000
    mtu: 1.5KB
    # TODO remove. not needed for veth, only for UDP
    destination: "127.0.0.1:34256"
schedule:
  !DeadlineRr
  slots:
    - vl: 1
      period: 1s
    - vl: 2
      period: 500ms
