[package]
name = "np-linux-echo-example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
network-partition = { path = "../../core" }
network-partition-linux = { path = "../../linux" }
apex-echo = { path = "../../echo" }
apex-rs = { git = "https://github.com/aeronautical-informatics/apex-rs.git", branch = "main" }
apex-rs-linux = { git = "https://github.com/dadada/apex-linux.git", branch = "stable-for-master-thesis" }
apex-rs-postcard = { git = "https://github.com/aeronautical-informatics/apex-rs-postcard.git", branch = "main" }
serde = { version = "1.0", features = ["derive"] }
log = "0"
once_cell = "1.17"

[build-dependencies]
network-partition-config = { path = "../../gen-config" }
serde_yaml = "0.9"
quote = "1"
proc-macro2 = "1"
