[package]
name = "np-zynq7000"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = [ "staticlib" ]

[dependencies]
network-partition = { path = "../../network-partition", features = [ "serde" ] }
network-partition-uart = { path = "../../network-partition-uart" }
apex-rs = { git = "https://github.com/aeronautical-informatics/apex-rs.git", branch = "main" }
apex-rs-xng = { git = "https://github.com/dadada/apex-rs-xng.git", branch = "xng-hypervisor-debug" }
log = { version = "0", default-features = false }
heapless = { version = "0.7" }
once_cell = { version = "1.17", default-features = false }
postcard = "1.0"
small-trace = { path = "../../small-trace" }
small-trace-gpio = { path = "../../small-trace-gpio" }
xng-rs-log = { path = "../../xng-rs-log" }


[build-dependencies]
network-partition = { path = "../../network-partition", feature = [ "serde" ] }
network-partition-config = { path = "../../network-partition-config" }
serde_yaml = "0.9"
quote = "1"
proc-macro2 = "1"
