# set defaults for all other jobs
default:
  tags: [nix]
  before_script:
    - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.dlr.de/".insteadOf "ssh://git@gitlab.dlr.de"
    - mkdir -p ~/.config/nix
    - echo 'accept-flake-config = true' >> ~/.config/nix/nix.conf

format:
  script:
    - nix develop --command treefmt --fail-on-change --no-cache

variables:
  CARGO_EXTR_ARGS: "--all-features -p network-partition -p network-partition-macros -p network-partition-uart -p network-partition-linux -p small-trace -p small-trace-gpio"

rust-test:
  script:
    # pre-seed build cache
    - nix develop --command cargo build $CARGO_EXTRA_ARGS
    - nix develop --command cargo build --release $CARGO_EXTRA_ARGS
    # generate docs
    - nix develop --command cargo doc --all-features --document-private-items $CARGO_EXTRA_ARGS
    - |
      cat << EOF > target/doc/index.html
      <meta http-equiv="Refresh" content="0; url='network_partition/index.html'"/>
      EOF
    # generate clippy report
    - nix develop --command cargo clippy --message-format=json $CARGO_EXTRA_ARGS > clippy-lints.json
    - nix develop --command gitlab-clippy clippy-lints.json --output code-quality-report.json
    # run tests
    - nix develop --command cargo nextest run --profile ci $CARGO_EXTRA_ARGS
    - mv target/nextest/ci/junit.xml junit-debug.xml
    - nix develop --command cargo nextest run --profile ci --release $CARGO_EXTRA_ARGS
    - mv target/nextest/ci/junit.xml junit-release.xml
  artifacts:
    paths:
      [clippy-lints.json, code-quality-report.json, junit-**.xml, target/doc]
    reports:
      codequality: code-quality-report.json
      junit: junit-*.xml

nix-flake-check:
  script:
    - nix flake check --print-build-logs
