stages:
  - check
  - build
  - test

# set defaults for all other jobs
default:
  tags: [nix]
  before_script:
    - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.dlr.de/".insteadOf "ssh://git@gitlab.dlr.de"
    - mkdir -p ~/.config/nix
    - echo 'accept-flake-config = true' >> ~/.config/nix/nix.conf
    - echo 'experimental-features = nix-command flakes' >> ~/.config/nix/nix.conf

checks:
  stage: check
  script:
    - nix develop --command run-checks

variables:
  CARGO_EXTR_ARGS: "--all-features"

rust-test:
  stage: test
  script:
    # pre-seed build cache
    - nix develop --command cargo build $CARGO_EXTRA_ARGS
    - nix develop --command cargo build --release $CARGO_EXTRA_ARGS
    # generate docs
    - nix develop --command cargo doc --all-features --document-private-items $CARGO_EXTRA_ARGS
    - |
      cat << EOF > target/doc/index.html
      <meta http-equiv="Refresh" content="0; url='network_partition/index.html'"/>
      EOF
    # generate clippy report
    - nix develop --command cargo clippy --message-format=json $CARGO_EXTRA_ARGS > clippy-lints.json
    - nix develop --command gitlab-clippy clippy-lints.json --output code-quality-report.json
    # run tests
    - nix develop --command cargo nextest run --profile ci $CARGO_EXTRA_ARGS
    - mv target/nextest/ci/junit.xml junit-debug.xml
    - nix develop --command cargo nextest run --profile ci --release $CARGO_EXTRA_ARGS
    - mv target/nextest/ci/junit.xml junit-release.xml
  artifacts:
    paths:
      [clippy-lints.json, code-quality-report.json, junit-**.xml, target/doc]
    reports:
      codequality: code-quality-report.json
      junit: junit-*.xml

run-nixos-integration-test:
  stage: test
  script:
    - nix develop --command run-nixos-integration-test

build-crates:
  stage: build
  script:
    - nix develop --command cargo build $CARGO_EXTRA_ARGS

build-xng-images:
  stage: build
  script:
    - nix develop --command build-xng-images
