[package]
name = "network_partition"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
apex-rs = { git = "https://github.com/aeronautical-informatics/apex-rs.git", branch = "main" }
apex-rs-linux = { git = "ssh://git@github.com:/aeronautical-informatics/apex-linux.git", branch = "main" }
log = "0"
once_cell = "1.16"
humantime = "2.1"