[workspace]
resolver = "2"
members = [
  "apex-throughput",
  "apex-echo",
  "dummy-hypervisor",
  "echo-router",
  "network-partition",
  "network-partition-linux",
  "network-partition-macros",
  "network-partition-uart",
  "small-trace",
  "small-trace-gpio",
]
default-members = [  
  "apex-throughput",
  "apex-echo",
  "echo-router",
  "network-partition",
  "network-partition-linux",
  "network-partition-macros",
  "network-partition-uart",
  "small-trace",
  "small-trace-gpio",
]

[workspace.dependencies]
a653rs = "0.3"
log = "0"
# For UDP socket support
a653rs-linux = { git = "https://github.com/dadada/apex-linux.git", branch = "udp-network-driver", default-features = false }
# A bit newer than the published version
uart_xilinx = { git = "https://github.com/duskmoon314/uart-rs.git", branch = "main", default-features = false }
# These are not on crates.io
a653rs-postcard = { git = "https://github.com/DLR-FT/a653rs-postcard.git", branch = "main", default-features = false }
a653rs-xng = { git = "https://github.com/DLR-FT/a653rs-xng.git", branch = "main", default-features = false }
once_cell = { version = "1.17", default-features = false }
serde = { version = "1.0", default-features = false }
xng-rs-log = { git = "https://github.com/DLR-FT/xng-rs-log.git", branch = "main", default-features = false }
