[workspace]
resolver = "2"
members = [
  "coraz7",
  "echo",
  "gen-config",
  "core",
  "linux",
  "xng",
  "examples/echo-linux",
  "examples/np-zynq7000",
  "examples/echo-client-zynq7000",
  "examples/echo-server-zynq7000",
  "trace"
]
default-members = [  
  "trace",
  "coraz7",
  "echo",
  "gen-config",
  "core",
  "linux",
  "xng",
  "examples/echo-linux",
  #"examples/zynq7000"
]
