[workspace]
resolver = "2"
members = [
  "apex-throughput",
  "apex-echo",
  "examples/echo-client-zynq7000",
  "examples/echo-linux",
  "examples/echo-server-zynq7000",
  "examples/np-zynq7000",
  "examples/throughput-zynq7000",
  "network-partition",
  "network-partition-config",
  "network-partition-linux",
  "network-partition-uart",
  "small-trace",
  "small-trace-gpio",
  "xng-rs-log",
]
default-members = [  
  "apex-throughput",
  "apex-echo",
  #"examples/echo-client-zynq7000",
  "examples/echo-linux",
  #"examples/echo-server-zynq7000",
  #"examples/np-zynq7000",
  #"examples/throughput-zynq7000",
  "network-partition",
  "network-partition-config",
  "network-partition-linux",
  "network-partition-uart",
  "small-trace",
  "small-trace-gpio",
  "xng-rs-log",
]

[patch.crates-io]
a653rs = { git = "https://github.com/DLR-FT/a653rs.git", branch = "main" }
a653rs-linux = { git = "https://github.com/dadada/apex-linux.git", branch = "dev/tim" }
# a653rs-linux = { git = "https://github.com/DLR-FT/a653rs-linux.git", branch = "main" }
uart_xilinx = { git = "https://github.com/duskmoon314/uart-rs.git", branch = "main"}
a653rs-postcard = { git = "https://github.com/DLR-FT/a653rs-postcard.git", branch = "main" }
a653rs-xng = { git = "https://github.com/DLR-FT/a653rs-xng.git", branch = "main" }
