[workspace]
resolver = "2"
members = [
  "echo",
  "gen-config",
  "core",
  "linux",
  "xng",
  "examples/echo",
  "examples/np-zynq7000"
]
default-members = [  
  "echo",
  "gen-config",
  "core",
  "linux",
  "xng",
  "examples/echo",
  #"examples/zynq7000"
]