[workspace]
resolver = "2"
members = [
  "core",
  "echo",
  "examples/echo-client-zynq7000",
  "examples/echo-linux",
  "examples/echo-server-zynq7000",
  "examples/np-zynq7000",
  "examples/throughput-zynq7000",
  "network-partition-config",
  "network-partition-linux",
  "network-partition-uart",
  "small-trace",
  "small-trace-gpio",
  "throughput",
  "xng-rs-log",
]
default-members = [  
  "core",
  "echo",
  #"examples/echo-client-zynq7000",
  "examples/echo-linux",
  #"examples/echo-server-zynq7000",
  #"examples/np-zynq7000",
  #"examples/throughput-zynq7000",
  "network-partition-config",
  "network-partition-linux",
  "network-partition-uart",
  "small-trace",
  "small-trace-gpio",
  "throughput",
  "xng-rs-log",
]

[patch."https://github.com/aeronautical-informatics/apex-rs.git"]
apex-rs = { git = "https://github.com/dadada/apex-rs.git", branch = "dev/fix-refresh-period-magic-value" }
