[workspace]
resolver = "2"
members = [
  "coraz7",
  "echo",
  "gen-config",
  "core",
  "linux",
  "xng",
  "examples/echo-linux",
  "examples/np-zynq7000",
  "examples/echo-client-zynq7000",
  "examples/echo-server-zynq7000",
  "trace"
]
default-members = [  
  "trace",
  "coraz7",
  "echo",
  "gen-config",
  "core",
  "linux",
  "xng",
  "examples/echo-linux",
  #"examples/zynq7000"
]

[patch."https://github.com/aeronautical-informatics/apex-rs.git"]
apex-rs = { git = "https://github.com/dadada/apex-rs.git", branch = "dev/fix-refresh-period-magic-value" }
