major_frame: 1s
partitions:
  - id: 0
    name: Foo
    duration: 10ms
    offset: 0ms
    period: 500ms
    image: target/x86_64-unknown-linux-musl/release/network_partition
  - id: 1
    name: Bar
    offset: 100ms
    duration: 10ms
    image: target/x86_64-unknown-linux-musl/release/network_partition
    period: 1s
channel:
  - !Sampling
    name: Hello
    msg_size: 10KB
    source: Foo
    destination:
      - Bar