major_frame: 1s
partitions:
  - id: 0
    name: Echo
    duration: 300ms
    offset: 0ms
    period: 1s
    image: echo-linux-server-sampling
  - id: 1
    name: Network
    duration: 300ms
    offset: 400ms
    period: 1s
    image: router-echo-server-linux
    sockets:
      - type: udp
        address: "0.0.0.0:8082"
  - id: 3
    name: Cfgr
    duration: 300ms
    offset: 700ms
    period: 1s
    image: configurator-linux
    mounts:
      - ["/etc/route-table.json", "/route-table.json"]
channel:
  - !Sampling
    name: EchoRequest
    msg_size: 1KB
    source: { partition: Network, port: EchoRequest }
    destination:
      - { partition: Echo, port: EchoRequest }
  - !Sampling
    name: EchoReply
    msg_size: 1KB
    source: { partition: Echo, port: EchoReply }
    destination:
      - { partition: Network, port: EchoReply }
  - !Sampling
    name: RouterConfig
    msg_size: 1KB
    source:  { partition: Cfgr, port: RouterConfig }
    destination:
      -  { partition: Network, port: RouterConfig }
