major_frame: 1s
partitions:
  - id: 1
    name: EchoClient
    duration: 300ms
    offset: 0ms
    period: 1s
    image: echo
  - id: 2
    name: Network
    duration: 300ms
    offset: 350ms
    period: 1s
    image: router-echo-client-linux
    sockets:
      - type: udp
        address: "0.0.0.0:8081"
  - id: 3
    name: Cfgr
    duration: 300ms
    offset: 650ms
    period: 1s
    image: configurator-linux
    mounts:
      - ["/etc/route-table.json", "/route-table.json"]
channel:
  - !Sampling
    name: EchoRequest
    msg_size: 1KB
    source: { partition: EchoClient, port: EchoSend }
    destination:
      - { partition: Network, port: EchoRequest }
  - !Sampling
    name: EchoReply
    msg_size: 1KB
    source: { partition: Network, port: EchoReply }
    destination:
      - { partition: EchoClient, port: EchoReceive }
  - !Sampling
    name: RouterConfig
    msg_size: 1KB
    source:  { partition: Cfgr, port: RouterConfig }
    destination:
      -  { partition: Network, port: RouterConfig }
