[package]
name = "throughput-zynq7000"
version = "0.1.0"
edition = "2021"

[features]
sender = []
receiver = []

[lib]
crate-type = [ "staticlib" ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
apex-throughput = { path = "../../apex-throughput" }
a653rs = "0"
a653rs-xng = "0"
small-trace-gpio = { path = "../../small-trace-gpio" }
once_cell = { version = "1.17", default-features = false }
log = "0"
xng-rs-log = { path = "../../xng-rs-log" }
