[package]
name = "throughput-zynq7000"
version = "0.1.0"
edition = "2021"

[features]
sender = []
receiver = []

[lib]
crate-type = [ "staticlib" ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
apex-throughput = { path = "../../throughput" }
apex-rs = { git = "https://github.com/aeronautical-informatics/apex-rs.git", branch = "main" }
apex-rs-xng = { git = "https://github.com/dadada/apex-rs-xng.git", branch = "xng-hypervisor-debug" }
coraz7 = { path = "../../coraz7" }
once_cell = { version = "1.17", default-features = false }
log = "0"
