[package]
name = "dummy-hypervisor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
a653rs.workspace = true

[dependencies.a653rs-router]
path = "../a653rs-router"
default-features = false