stack_size:
  periodic_process: 1MB
virtual_links:
  - id: 1
    rate: 10000
    msg_size: 1KB
    interfaces: [ "veth0" ]
    ports:      
      - !SamplingPortSource
        channel: EchoReply
      - !SamplingPortDestination
        channel: EchoRequest
        validity: 1s
  - id: 2
    rate: 10000
    msg_size: 1KB
    interfaces: [ "veth0" ]
    ports: []
interfaces:
  - name: veth0
    rate: 10000000
    mtu: 1.5KB
