major_frame: 1s
partitions:
  - id: 1
    name: EchoClient
    duration: 300ms
    offset: 0ms
    period: 1s
    image: echo
  - id: 2
    name: Router
    duration: 300ms
    offset: 350ms
    period: 1s
    image: router
    mounts:
      - [ "/etc/router.yml", "/router.yml" ]
    sockets:
      - type: udp
        address: "0.0.0.0:8081"
channel:
  - !Queuing
    name: EchoRequest
    msg_size: 1KB
    msg_num: 10
    discipline: Fifo
    source: { partition: EchoClient, port: EchoSend }
    destination: { partition: Router, port: EchoRequest }
  - !Queuing
    name: EchoReply
    msg_size: 1KB
    msg_num: 10
    discipline: Fifo
    source: { partition: Router, port: EchoReply }
    destination: { partition: EchoClient, port: EchoReceive }
