[package]
name = "a653rs-router"
version = "0.1.0"
edition = "2021"

[features]
serde = [ "dep:postcard", "dep:serde", "heapless/serde", "bytesize?/serde" ]
macros = [ "dep:a653rs-router-macros", "serde" ]
partition = [ "macros", "dep:a653rs-router-partition-macros" ]

[dependencies]
a653rs.workspace = true
heapless.workspace = true
log = "0"
humantime-serde = { version = "1", optional = true }
serde = { version = "1.0", default-features = false, features = ["derive"], optional = true }
bytesize = { version = "1.1.0", optional = true }
small-trace = { path = "../small-trace" }
postcard = { workspace = true, optional = true, features = ["heapless"] }
a653rs-router-macros = { path = "../a653rs-router-macros", optional = true }
a653rs-router-partition-macros = { path = "../a653rs-router-partition-macros", optional = true }

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "doc_cfg"]
