[package]
name = "network-partition"
version = "0.1.0"
edition = "2021"

[dependencies]
apex-rs = { git = "https://github.com/aeronautical-informatics/apex-rs.git", branch = "main"}
bytesize = { version = "1.1" }
heapless = { version = "0.7" }
log = "0"
