[package]
name = "echo-xng"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = [ "staticlib" ]

[dependencies]
a653rs.workspace = true
a653rs-xng.features= ["panic_handler"]
a653rs-xng.workspace = true
echo = { path = "../echo" }
log.workspace = true
xng-rs-log.workspace = true
