stack_size:
  aperiodic_process: 15KB
virtual_links:
  - id: 1
    msg_size: 100
    interfaces: [ ]
    ports:
      - !SamplingPortDestination
        channel: EchoReplySrv
        validity: 10s
      - !SamplingPortSource
        channel: EchoReplyCl
  - id: 2
    msg_size: 100
    interfaces: [ ]
    ports:      
      - !SamplingPortDestination
        channel: EchoRequestCl
        validity: 10s
      - !SamplingPortSource
        channel: EchoRequestSrv
schedule:
  !DeadlineRr
  slots:
    - vl: 1
      period: 1s
    - vl: 2
      period: 500ms