stack_size:
  periodic_process: 15000B
virtual_links:
  - id: 1
    rate: 1s
    msg_size: 100B
    interfaces: [ ]
    ports:
      - !SamplingPortDestination
        channel: EchoReplySrv
        validity: 10s
      - !SamplingPortSource
        channel: EchoReplyCl
  - id: 2
    rate: 500ms
    msg_size: 100B
    interfaces: [ ]
    ports:      
      - !SamplingPortDestination
        channel: EchoRequestCl
        validity: 10s
      - !SamplingPortSource
        channel: EchoRequestSrv
