cargo-features = [ "per-package-target" ]

[package]
name = "np-zynq7000"
version = "0.1.0"
edition = "2021"
forced-target = "armv7a-none-eabi"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = [ "staticlib" ]

[dependencies]
network-partition = { path = "../../core" }
network-partition-xng = { path = "../../xng" }
apex-rs = { git = "https://github.com/aeronautical-informatics/apex-rs.git", branch = "main" }
apex-rs-xng = { git = "https://github.com/dadada/apex-rs-xng.git", branch = "xng-hypervisor-debug" }
log = "0"
heapless = { version = "0.7.16" }
once_cell = { version = "1.17", default-features = false }

[build-dependencies]
network-partition-config = { path = "../../gen-config" }
serde_yaml = "0.9"
quote = "1"
proc-macro2 = "1"
