[package]
name = "echo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
a653rs-postcard.workspace = true
log = "0"
small-trace = { path = "../../small-trace" }

[dependencies.a653rs]
workspace = true

[dependencies.serde]
features = ["derive"]
workspace = true
