major_frame: 20s # Messages become invalid after major frame?
partitions:
  - id: 0
    name: Echo
    duration: 10ms
    offset: 0ms
    period: 1s
    image: target/x86_64-unknown-linux-musl/release/echo
  - id: 1
    name: Network
    duration: 10ms
    offset: 1010ms
    period: 1s
    image: target/x86_64-unknown-linux-musl/release/network-partition-linux
channel:
  - !Sampling
    name: EchoRequest
    msg_size: 10KB
    source: Echo
    destination:
      - Network
  - !Sampling
    name: EchoReply
    msg_size: 10KB
    source: Network
    destination:
      - Echo