[package]
name = "network-partition-echo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
network-partition = { path = "../../core" }
network-partition-linux = { path = "../../linux" }
apex-rs = { git = "https://github.com/aeronautical-informatics/apex-rs.git", branch = "main" }
apex-rs-linux = { git = "https://github.com/dadada/apex-linux.git", branch = "stable-for-master-thesis" }
log = "0"
heapless = "0.7"
bytesize = "1.1"
once_cell = "1"

[build-dependencies]
network-partition-config = { path = "../../config" }
serde_yaml = "0.9"
quote = "1"