stack_size:
  periodic_process: 1MB
ports:
  - !SamplingPortDestination
    channel: EchoRequest
    msg_size: 10KB
    validity: 1s
    virtual_link: 0
  - !SamplingPortSource
    channel: EchoReply
    msg_size: 10KB
    virtual_link: 0
virtual_links:
  # - Client Partition <-> Client Partition should be done through hypervisor directly, hypervisor should support reconfiguration.
  # - A sampling port destination is created by the network partition, needs corresponding configuration for hypervisor.
  - id: 0 # destination virtual link
    # TODO Name?
    # minimum period -> max data rate
    rate: 1KB # kB/s
    msg_size: 1KB # TODO The message size could be derived from  the configuration of the channel
interfaces:
  - id: 0
    rate: 100KB
    mtu: 1.5KB
