stack_size:
  periodic_process: 1MB
virtual_links:
  - id: 1
    rate: 10000
    msg_size: 1KB
    interfaces: [ "veth0", "veth1" ]
    ports:      
      - !SamplingPortSource
        channel: EchoReply
  - id: 2
    rate: 10000
    msg_size: 1KB
    ports:
      - !SamplingPortDestination
        channel: EchoRequest
        validity: 1s
    interfaces: [ "veth0", veth1" ]
interfaces:
  - name: veth0
    rate: 10000000
    mtu: 1.5KB
  - name: veth1
    rate: 10000000
    mtu: 1.5KB
