stack_size:
  periodic_process: 1MB
ports:
  - !SamplingPortDestination
    channel: EchoRequest
    msg_size: 10KB
    validity: 1s
    virtual_link: 1
  - !SamplingPortSource
    channel: EchoReply
    msg_size: 10KB
    virtual_link: 1
virtual_links:
  - id: 1
    rate: 10000
    msg_size: 1KB
    interfaces: [ "veth0", "veth1" ]
  - id: 2
    rate: 10000
    msg_size: 1KB
    interfaces: []
interfaces:
  - name: veth0
    rate: 10000000
    mtu: 1.5KB
  - name: veth1
    rate: 10000000
    mtu: 1.5KB
