[package]
name = "network-partition-linux"
version = "0.1.0"
edition = "2021"

[dependencies]
network-partition = { path = "../network-partition" }
a653rs-linux.workspace = true
once_cell = "1.17"
log = "0"
heapless = "0.7"
bytesize = "1.1"
small-trace = { path = "../small-trace" }
