[package]
name = "coraz7"
description = "Platform specific structures"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
volatile-register = "0.2"
small-trace = { path = "../trace" }
