[package]
name = "a653rs-router-zynq7000"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
a653rs-router = { path = "../a653rs-router" }
log = "0"
once_cell = { version = "1.17", default-features = false }
uart_xilinx.workspace = true
heapless = { version = "0.7", default-features = false }
corncobs = { version = "0.1" }
crc16 = { version = "0.4.0", default-features = false }
small-trace = { path = "../small-trace" }
