stack_size:
  aperiodic_process: 15000
virtual_links:
  - id: 2
    msg_size: 100
    interfaces: [ "uart0" ]
    ports:
      - !SamplingPortDestination
        channel: EchoReplySrv
        validity: 10s
  - id: 1
    msg_size: 100
    ports:
      - !SamplingPortSource
        channel: EchoRequestSrv
interfaces:
  - !Uart
    id: 1
    name: "uart0"
    mtu: 1500
schedule:
  !DeadlineRr
  slots:
    - vl: 1
      period: 1s
    - vl: 2
      period: 500ms
