stack_size:
  aperiodic_process: 15KB
virtual_links:
  - id: 2
    rate: 500ms
    msg_size: 100
    interfaces: [ "uart0" ]
    ports:
      - !SamplingPortDestination
        channel: EchoReplySrv
        validity: 10s
  - id: 1
    rate: 1s
    msg_size: 100B
    ports:
      - !SamplingPortSource
        channel: EchoRequestSrv
interfaces:
  - !Uart
    id: 1
    name: "uart0"
    mtu: 1.5KB
