stack_size:
  aperiodic_process: 15KB0
virtual_links:
  - id: 2
    rate: 500ms
    msg_size: 100
    interfaces: [ "veth0" ]
    ports:
      - !SamplingPortDestination
        channel: EchoReplySrv
        validity: 10s
  - id: 1
    rate: 1s
    msg_size: 100B
    ports:      
      - !SamplingPortSource
        channel: EchoRequestSrv
interfaces:
  - id: 1
    name: veth0
    rate: 10000000
    mtu: 1.5KB
    # TODO remove. not needed for veth, only for UDP
    destination: "127.0.0.1:34256"
