[package]
name = "network-partition-linux"
version = "0.1.0"
edition = "2021"

[dependencies]
network-partition = { path = "../core" }
apex-rs = { git = "https://github.com/aeronautical-informatics/apex-rs.git", branch = "main" }
apex-rs-linux = { git = "ssh://git@github.com:/aeronautical-informatics/apex-linux.git", branch = "main" }
apex-rs-postcard = { git = "ssh://git@github.com:/aeronautical-informatics/apex-rs-postcard.git", branch = "main" }
serde = "1.0"
log = "0"
once_cell = "1.16"

