stack_size:
  aperiodic_process: 15KB
virtual_links:
  - id: 1
    msg_size: 100
    interfaces: [ ]
    fifo_depth: 100
    ports:
      - !QueuingPortReceiver
        channel: TrafficSN
      - !QueuingPortSender
        channel: TrafficRN
schedule:
  !DeadlineRr
  slots:
    - vl: 1
      period: 4ms
