period:
  secs: 1
  nanos: 0
time_capacity:
  secs: 0
  nanos: 300000
stack_size: 20000
virtual_links:
  1:
    period:
      secs: 0
      nanos: 100000
    source: EchoRequestCl
    destinations: [ EchoRequestSrv ]
  2:
    period:
      secs: 0
      nanos: 100000
    source: EchoReplySrv
    destinations: [ EchoReplyCl ]
ports:
  EchoRequestCl:
    !queuing_in
    msg_size: 1000
    msg_count: 10
    discipline: fifo
  EchoRequestSrv:
    !queuing_out
    msg_size: 1000
    msg_count: 10
    discipline: fifo
  EchoReplySrv:
    !queuing_in
    msg_size: 1000
    msg_count: 10
    discipline: fifo
  EchoReplyCl:
    !queuing_out
    msg_size: 1000
    msg_count: 10
    discipline: fifo
