name: Run checks

on:
  pull_request:
  push:
    branches: [main]

jobs:
  nix-checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-stable
          extra_nix_config: |
            experimental-features = nix-command flakes kvm nixos-test
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - name: Cache Nix store
        uses: actions/cache@v3
        id: nix-cache
        with:
          path: /tmp/nixcache
          key: nix-${{ runner.os }}
      - name: Import Nix store cache
        if: "steps.nix-cache.outputs.cache-hit == 'true'"
        run: nix copy --no-check-sigs --from /tmp/nixcache --all
      - name: cargo-fmt
        run: nix build .#checks.x86_64-linux.cargo-fmt
      - name: nixpkgs-fmt
        run: nix build .#checks.x86_64-linux.nixpkgs-fmt
      - name: test-run-echo-scoped
        run: nix develop -c test-run-echo-scoped
      - name: Export Nix store cache
        if: "steps.nix-cache.outputs.cache-hit != 'true'"
        run: |
          nix copy --no-check-sigs --to /tmp/nixcache .#devShells.x86_64-linux.default
