name: Continuous Integration

on:
  pull_request:
  push:
    branches: [main]

jobs:
  devshell:
    name: Build devshell
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check Cgroup
        run: systemd-run --use --scope cat /proc/self/cgroup
      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-stable
          extra_nix_config: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v11
        with:
          name: network-partition
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Build development shell
        run: nix build .#devShells.x86_64-linux.default

  check:
    name: Format checks
    needs: devshell
    runs-on: ubuntu-latest
    env:
      RUST_LOG: trace
    steps:
      - uses: actions/checkout@v2
      - name: Check Cgroup
        run: systemd-run --use --scope cat /proc/self/cgroup
      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-stable
          extra_nix_config: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v11
        with:
          name: network-partition
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
       # Check
      - name: Clippy
        run: nix develop -c check-clippy
      - name: Flake checks
        run: nix develop -c check-flake
      - name: Format check
        run: nix develop -c check-format
      - name: Find unused dependencies
        run: nix develop -c check-udeps

  build-and-test:
    name: Build and test
    needs: devshell
    runs-on: ubuntu-latest
    env:
      RUST_LOG: trace
    steps:
      - uses: actions/checkout@v2
      - name: Check Cgroup
        run: systemd-run --use --scope cat /proc/self/cgroup
      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-stable
          extra_nix_config: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v11
        with:
          name: network-partition
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Build echo partition
        run: nix develop -c build-echo
      - name: Build network partition
        run: nix develop -c build-network-partition
      - name: Build network partition for linux hypervisor
        run: nix develop -c build-network-partition-linux
      - name: Run unit tests
        run: nix develop -c test-unit
      - name: Run echo example
        run: nix develop -c test-run-echo

  build-doc:
    name: Build documentation
    needs: devshell
    runs-on: ubuntu-latest
    env:
      RUST_LOG: trace
    steps:
      - uses: actions/checkout@v2
      - name: Check Cgroup
        run: systemd-run --use --scope cat /proc/self/cgroup
      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-stable
          extra_nix_config: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v11
        with:
          name: network-partition
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Build documenation
        run: nix develop -c build-doc
