name: Nix Related Actions

on:
  pull_request:
  push:
    branches: [main]

jobs:
  check:
    name: Checks
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        command:
          - treefmt --fail-on-change
          - cargo check --all-features
          - cargo clippy --all-features
          - cargo test --all-features
          - cargo doc --all-features
          - run-nixos-integration-test
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v26
        with:
          nix_path: nixpkgs=channel:nixos-stable
          extra_nix_config:
            github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: ${{ matrix.command }}
        run: nix develop --command ${{ matrix.command }}
