name: Continuous Integration

on:
  pull_request:
  push:
    branches: [main]

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    env:
      RUST_LOG: trace
    steps:
      - uses: actions/checkout@v2
      - name: Check Cgroup
        run: systemd-run --use --scope cat /proc/self/cgroup
      - uses: cachix/install-nix-action@v15
        with:
          nix_path: nixpkgs=channel:nixos-stable
          extra_nix_config: |
            experimental-features = nix-command flakes
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
            system-features = nixos-test benchmark big-parallel kvm
      - uses: cachix/cachix-action@v11
        with:
          name: network-partition
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Checks
        run: nix flake check
