[package]
name = "echo-server-zynq7000"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = [ "staticlib" ]

[dependencies]
apex-echo = { path = "../../apex-echo" }
a653rs = "0.2"
a653rs-xng = "0"
once_cell = { version = "1.17", default-features = false }
log = "0"
small-trace-gpio = { path = "../../small-trace-gpio" }
small-trace = { path = "../../small-trace" }
xng-rs-log = { path = "../../xng-rs-log" }
